version: '3.8'  
services:
  server1:
    build: ./NoHonbab-backend
    ports: 
      - '8111:80'
    volumes:
      - nohonbab-backend-logs:/app/logs
      - ./NoHonbab-backend:/app
      - /app/node_modules
    env_file:
      - ./envs/backend.env
    platform: linux/amd64
  server2:
    build: ./NoHonbab-matcher
    ports:
      - '8112:8112'
    volumes:
      - nohonbab-match-logs:/app/logs
      - ./NoHonbab-matcher:/app
      - /app/node_modules
    env_file:
      - ./envs/matcher.env
    platform: linux/amd64
    depends_on:
      - server1
volumes:
  nohonbab-backend-logs:
  nohonbab-match-logs: